<script>
<?php
/**
 * Filter main UI JS config.
 * @see ba_cheetah_ui_js_config
 */
echo 'BACheetahConfig              = ' . BACheetahUtils::json_encode( apply_filters('ba_cheetah_ui_js_config', array(
	'adminUrl'                   => admin_url(),
	'ajaxNonce'                  => wp_create_nonce( 'ba_cheetah_ajax_update' ),
	'builderEnabled'             => get_post_meta( $post_id, '_ba_cheetah_enabled', true ) ? true : false,
	'colorPresets'               => BACheetahModel::get_color_presets(),
	'customImageSizeTitles'      => apply_filters( 'image_size_names_choose', array() ),
	'debug'                      => BACheetah::is_debug(),
	'enabledTemplates'           => 'core',
	'global'                     => $global_settings,
	'help'                       => BACheetahModel::get_help_button_settings(),
	'homeUrl'                    => home_url(),
	'enqueueMethod'              => BACheetahModel::get_asset_enqueue_method(),
	'isRtl'                      => is_rtl(),
	'isUserTemplate'             => false,
	'autenticated'				 => BA_CHEETAH_AUTENTICATED === true,
	'isBuilderallUser'			 => BA_CHEETAH_BUILDERALL === true,
	'isProUser'					 => BA_CHEETAH_PRO === true,
	'modSecFix'                  => ( defined( 'BA_CHEETAH_MODSEC_FIX' ) && BA_CHEETAH_MODSEC_FIX ),
	'MaxInputVars'               => BA_CHEETAH_Debug::safe_ini_get( 'max_input_vars' ),
	'moduleGroups'               => BACheetahModel::get_module_groups(),
	'modulesRowInsideEnabled'	 => BACheetahModel::get_modules_supports_row_inside(),
	'nestedColumns'              => ( ! defined( 'BA_CHEETAH_NESTED_COLUMNS' ) || BA_CHEETAH_NESTED_COLUMNS ),
	'newUser'                    => BACheetahModel::is_new_user(),
	'pluginUrl'                  => BA_CHEETAH_URL,
	'relativePluginUrl'          => BACheetahModel::get_relative_plugin_url(),
	'postId'                     => $post_id,
	'postStatus'                 => get_post_status(),
	'postType'                   => get_post_type(),
	'services'                   => array(),
	'simpleUi'                   => $simple_ui ? true : false,
	'upgradeUrl'                 => BACheetahModel::get_upgrade_url(),
	'landingpageUrl'       	 	 => BACheetahModel::get_landingpage_url(),
	'userCanEditGlobalTemplates' => BACheetahUserAccess::current_user_can( 'global_node_editing' ),
	'userCanPublish'             => current_user_can( 'publish_posts' ),
	'userSettings'               => BACheetahUserSettings::get(),
	'userTemplateType'           => BACheetahModel::get_user_template_type(),
	'brandingIcon'               => BACheetahModel::get_branding_icon(),
	'url'                        => get_permalink(),
	'editUrl'                    => add_query_arg( 'ba_builder', '', get_permalink() ),
	'shortlink'                  => add_query_arg( 'ba_builder', '', BACheetahUtils::get_safe_url() ),
	'previewUrl'                 => add_query_arg( 'ba_cheetah_preview', '', get_permalink() ),
	'layoutHasDraftedChanges'    => BACheetahModel::layout_has_drafted_changes(),
	'panelData'                  => BACheetahUIContentPanel::get_panel_data(),
	'contentItems'               => BACheetahUIContentPanel::get_content_elements(),
	'mainMenu'                   => BACheetah::get_main_menu_data(),
	'keyboardShortcuts'          => BACheetah::get_keyboard_shortcuts(),
	'isCustomizer'               => is_customize_preview(),
	'showToolbar'                => is_customize_preview() ? false : true,
	'shouldRefreshOnPublish'     => BACheetah::should_refresh_on_publish(),
	'googleFontsUrl'             => apply_filters( 'ba_cheetah_google_fonts_domain', '//fonts.googleapis.com/' ) . 'css?family=',
	'wp_editor'                  => BACheetah::get_wp_editor(),
	'rowResize'                  => BACheetahModel::get_row_resize_settings(),
	// 'notifications'              => BACheetahNotifications::get_notifications(),
	'notifications'              => array(),
	'isWhiteLabeled'             => BACheetahModel::is_white_labeled(),
	'inlineEnabled'              => BACheetahModel::is_inline_enabled(),
	'CheckCodeErrors'            => BACheetahModel::is_codechecking_enabled(),
	'AceEditorSettings'          => BACheetahModel::ace_editor_settings(),
	'optionSets'                 => apply_filters( 'ba_cheetah_shared_option_sets', array() ),
	'presets'                    => BACheetahSettingsPresets::get_presets(),
	'FontWeights'                => BACheetahFonts::get_font_weight_strings(),
	'statsEnabled'               => get_site_option( 'ba_cheetah_usage_enabled', false ),
	'rememberTab'                => apply_filters( 'ba_cheetah_remember_settings_tabs_enabled', true ),
	'select2Enabled'             => apply_filters( 'ba_cheetah_select2_enabled', true ),
	'uploadTypes'                => apply_filters( 'ba_cheetah_media_modal_types', array(
		'image' => 'image',
		'video' => 'video',
	) ),
	'userCaps'                   => array(
		'unfiltered_html'        => current_user_can( 'unfiltered_html' ),
		'global_unfiltered_html' => defined( 'DISALLOW_UNFILTERED_HTML' ) && DISALLOW_UNFILTERED_HTML ? true : false,
	),
	'responsiveIgnore'           => apply_filters( 'ba_cheetah_responsive_ignore', array(
		'ba-cheetah-preview',
		'ba-cheetah-theme-builder',
		'/wp-includes/',
		'/wp-admin/',
		'admin-bar-inline-css',
		'ace-tm',
		'ace_editor.css',
	)),
) ) ) . ';';

/**
 * Filter UI JS Strings.
 * @see ba_cheetah_ui_js_strings
 */
echo 'BACheetahStrings             = ' . BACheetahUtils::json_encode( apply_filters('ba_cheetah_ui_js_strings', array(
	'actionsLightboxTitle'           => esc_attr__( 'What would you like to do?', 'ba-cheetah' ),
	/* translators: %s: field name */
	'addField'                       => esc_attr_x( 'Add %s', 'Field name to add.', 'ba-cheetah' ),
	/* translators: %s: preset color code */
	'alreadySaved'                   => esc_attr_x( '%s is already a saved preset.', '%s is the preset hex color code.', 'ba-cheetah' ),
	'audioSelected'                  => esc_attr__( 'Audio File Selected', 'ba-cheetah' ),
	/* translators: %d: number of files selected */
	'audioSelectedNum'               => esc_attr__( '%d Audio File Selected', 'ba-cheetah' ),
	'audiosSelected'                 => esc_attr__( 'Audio Files Selected', 'ba-cheetah' ),
	/* translators: %d: number of files selected (plural) */
	'audiosSelectedNum'              => esc_attr__( '%d Audio Files Selected', 'ba-cheetah' ),
	'blank'                          => esc_attr__( 'Blank', 'ba-cheetah' ),
	'cancel'                         => esc_attr__( 'Cancel', 'ba-cheetah' ),
	'changeTemplate'                 => esc_attr__( 'Change Template', 'ba-cheetah' ),
	'changeTemplateMessage'          => esc_attr__( 'When applying a template all elements on the page will be removed. Do you really want to do this?', 'ba-cheetah' ),
	'colorPresets'                   => esc_attr__( 'My colors', 'ba-cheetah' ),
	'colorPicker'                    => esc_attr__( 'Color Picker', 'ba-cheetah' ),
	'codeError'                      => esc_attr__( 'This code has errors. We recommend you fix them before saving.', 'ba-cheetah' ),
	'codeerrorhtml'                  => esc_attr__( 'You cannot add <script> or <iframe> tag here.', 'ba-cheetah' ),
	'codeErrorFix'                   => esc_attr__( 'Fix Errors', 'ba-cheetah' ),
	'codeErrorIgnore'                => esc_attr__( 'Save With Errors', 'ba-cheetah' ),
	'codeErrorDetected'              => esc_html__( 'We detected a possible issue here:', 'ba-cheetah' ),
	'column'                         => esc_attr__( 'Column', 'ba-cheetah' ),
	'contentSliderSelectLayout'      => esc_attr__( 'Please select either a background layout or content layout before submitting.', 'ba-cheetah' ),
	'contentSliderTransitionWarn'    => esc_attr__( 'Transition value should be lower than Delay value.', 'ba-cheetah' ),
	'countdownDateisInThePast'       => esc_attr__( 'Error! Please enter a date that is in the future.', 'ba-cheetah' ),
	'deleteAccount'                  => esc_attr__( 'Remove Account', 'ba-cheetah' ),
	'deleteAccountWarning'           => esc_attr__( 'Are you sure you want to remove this account? Other elements that are connected to it will be affected.', 'ba-cheetah' ),
	'deleteColumnMessage'            => esc_attr__( 'Do you really want to delete this column?', 'ba-cheetah' ),
	'deleteFieldMessage'             => esc_attr__( 'Do you really want to delete this item?', 'ba-cheetah' ),
	'deleteModuleMessage'            => esc_attr__( 'Do you really want to delete this element?', 'ba-cheetah' ),
	'deleteRowMessage'               => esc_attr__( 'Do you really want to delete this row?', 'ba-cheetah' ),
	'deleteTemplate'                 => esc_attr__( 'Do you really want to delete this template?', 'ba-cheetah' ),
	'deleteGlobalTemplate'           => esc_attr__( 'WARNING! You are about to delete a global template that may be linked to other pages. Do you really want to delete this template and unlink it?', 'ba-cheetah' ),
	'discard'                        => esc_attr__( 'Discard Changes and Exit', 'ba-cheetah' ),
	'discardMessage'                 => esc_attr__( 'Do you really want to discard these changes? All of your changes that are not published will be lost.', 'ba-cheetah' ),
	'done'                           => esc_attr__( 'Done', 'ba-cheetah' ),
	'draft'                          => esc_attr__( 'Save Changes and Exit', 'ba-cheetah' ),
	'duplicate'                      => esc_attr__( 'Duplicate', 'ba-cheetah' ),
	'duplicateLayout'                => esc_attr_x( 'Duplicate Layout', 'Duplicate page/post action label.', 'ba-cheetah' ),
	/* translators: %s: form field label */
	'editFormField'                  => esc_attr_x( 'Edit %s', '%s stands for form field label.', 'ba-cheetah' ),
	'editGlobalSettings'             => esc_attr__( 'Global Settings', 'ba-cheetah' ),
	'editLayoutSettings'             => esc_attr__( 'Layout CSS / Javascript', 'ba-cheetah' ),
	'emptyMessage'                   => esc_attr__( 'Drop a row layout or element to get started!', 'ba-cheetah' ),
	'enterValidDay'                  => esc_attr__( 'Error! Please enter a valid day.', 'ba-cheetah' ),
	'enterValidMonth'                => esc_attr__( 'Error! Please enter a valid month.', 'ba-cheetah' ),
	'enterValidYear'                 => esc_attr__( 'Error! Please enter a valid year.', 'ba-cheetah' ),
	'errorMessage'                   => esc_attr__( 'Builderall Builder caught the following JavaScript error. If Builderall Builder is not functioning as expected the cause is most likely this error. Please help us by disabling all plugins and testing Builderall Builder while reactivating each to determine if the issue is related to a third party plugin.', 'ba-cheetah' ),
	'fieldLoading'                   => esc_attr__( 'Field Loading...', 'ba-cheetah' ),
	'fullSize'                       => esc_attr__( 'Full Size', 'ba-cheetah' ),
	'getHelp'                        => esc_attr__( 'Get Help', 'ba-cheetah' ),
	'global'                         => esc_attr_x( 'Global', 'Indicator for global node templates.', 'ba-cheetah' ),
	'globalErrorMessage'             => __( '"{message}" on line {line} of {file}.', 'ba-cheetah' ),
	'insert'                         => esc_attr__( 'Insert', 'ba-cheetah' ),
	'large'                          => esc_attr__( 'Large', 'ba-cheetah' ),
	'manageTemplates'                => esc_attr__( 'Manage Templates', 'ba-cheetah' ),
	'medium'                         => esc_attr__( 'Medium', 'ba-cheetah' ),
	'mobile'                         => esc_attr__( 'Small', 'ba-cheetah' ),
	'module'                         => esc_attr__( 'Element', 'ba-cheetah' ),
	'moduleTemplateSaved'            => esc_attr__( 'Element Saved!', 'ba-cheetah' ),
	'move'                           => esc_attr__( 'Move', 'ba-cheetah' ),
	'newColumn'                      => esc_attr__( 'New Column', 'ba-cheetah' ),
	'newRow'                         => esc_attr__( 'New Row', 'ba-cheetah' ),
	'noneColorSelected'              => esc_attr__( 'Please enter a color first.', 'ba-cheetah' ),
	'noPresets'                      => esc_attr__( 'Add a color preset first.', 'ba-cheetah' ),
	'noResultsFound'                 => esc_attr__( 'No results found.', 'ba-cheetah' ),
	'noSavedRows'                    => esc_attr__( 'No saved rows found.', 'ba-cheetah' ),
	'noSavedModules'                 => esc_attr__( 'No saved elements found.', 'ba-cheetah' ),
	'ok'                             => esc_attr__( 'OK', 'ba-cheetah' ),
	'photoPage'                      => esc_attr__( 'Photo Page', 'ba-cheetah' ),
	'photoSelected'                  => esc_attr__( 'Photo Selected', 'ba-cheetah' ),
	/* translators: %d: number of selected */
	'photoSelectedNum'               => esc_attr__( '%d Photo Selected', 'ba-cheetah' ),
	'photosSelected'                 => esc_attr__( 'Photos Selected', 'ba-cheetah' ),
	/* translators: %d: number of selected (plural) */
	'photosSelectedNum'              => esc_attr__( '%d Photos Selected', 'ba-cheetah' ),
	'placeholder'                    => esc_attr__( 'Paste color here...', 'ba-cheetah' ),
	'placeholderSelect2'             => esc_attr__( 'Pick a font...', 'ba-cheetah' ),
	'pleaseWait'                     => esc_attr__( 'Please Wait...', 'ba-cheetah' ),
	/* translators: %s: preset color code */
	'presetAdded'                    => esc_attr_x( '%s added to palette!', '%s is the preset hex color code.', 'ba-cheetah' ),
	'publish'                        => esc_attr__( 'Publish Changes', 'ba-cheetah' ),
	'remove'                         => esc_attr__( 'Remove', 'ba-cheetah' ),
	'removePresetConfirm'            => esc_attr__( 'Are you sure?', 'ba-cheetah' ),
	'areYouSure'		             => esc_attr__( 'Are you sure?', 'ba-cheetah' ),
	/* translators: %s: time diff - 1 day/2 weeks */
	'revisionDate'                   => esc_attr_x( '%s ago', '%s is a time diff such as 1 day or 2 weeks.', 'ba-cheetah' ),
	/* translators: %s: author name */
	'revisionAuthor'                 => esc_attr_x( 'By %s', '%s is the author name.', 'ba-cheetah' ),
	'row'                            => esc_attr__( 'Row', 'ba-cheetah' ),
	'rowSettings'                    => esc_attr__( 'Row Settings', 'ba-cheetah' ),
	'rowTemplateSaved'               => esc_attr__( 'Row Saved!', 'ba-cheetah' ),
	'saveCoreTemplate'               => esc_attr__( 'Save Core Template', 'ba-cheetah' ),
	'save'                           => esc_attr__( 'Save', 'ba-cheetah' ),
	'saveAs'                         => esc_attr__( 'Save As', 'ba-cheetah' ),
	'saveColumn'                     => esc_attr__( 'Save Column', 'ba-cheetah' ),
	'saveModule'                     => esc_attr__( 'Save Element', 'ba-cheetah' ),
	'saveRow'                        => esc_attr__( 'Save Row', 'ba-cheetah' ),
	'saveTemplate'                   => esc_attr__( 'Save Template', 'ba-cheetah' ),
	'selectAudio'                    => esc_attr__( 'Select Audio', 'ba-cheetah' ),
	'selectPhoto'                    => esc_attr__( 'Select Photo', 'ba-cheetah' ),
	'selectPhotos'                   => esc_attr__( 'Select Photos', 'ba-cheetah' ),
	'selectVideo'                    => esc_attr__( 'Select Video', 'ba-cheetah' ),
	'selectOne'	                     => esc_attr__( 'Select One...', 'ba-cheetah' ),
	'noOptionsFound'				 => esc_attr__( 'No options found', 'ba-cheetah' ),
	'settingsHaveErrors'             => esc_attr__( 'These settings have errors.', 'ba-cheetah' ),
	'settingsHaveErrorsCorrect'      => esc_attr__( 'Please correct them before continuing.', 'ba-cheetah' ),
	'submitForReview'                => esc_attr__( 'Submit for Review', 'ba-cheetah' ),
	'subscriptionModuleAccountError' => esc_attr__( 'Please select an account before saving.', 'ba-cheetah' ),
	'subscriptionModuleConnectError' => esc_attr__( 'Please connect an account before saving.', 'ba-cheetah' ),
	'subscriptionModuleListError'    => esc_attr__( 'Please select a list before saving.', 'ba-cheetah' ),
	'subscriptionModuleTagsError'    => esc_attr__( 'Please enter at least one tag before saving.', 'ba-cheetah' ),
	'takeHelpTour'                   => esc_attr__( 'Take a Tour', 'ba-cheetah' ),
	'templateAppend'                 => esc_attr__( 'Append New Layout', 'ba-cheetah' ),
	'templateReplace'                => esc_attr__( 'Replace Existing Layout', 'ba-cheetah' ),
	'templateSaved'                  => esc_attr__( 'Template Saved!', 'ba-cheetah' ),
	'thumbnail'                      => esc_attr__( 'Thumbnail', 'ba-cheetah' ),
	'tourNext'                       => esc_attr__( 'Next', 'ba-cheetah' ),
	'tourEnd'                        => esc_attr__( 'Get Started', 'ba-cheetah' ),
	'start'							 => esc_attr__( 'Start', 'ba-cheetah' ),
	'tourMode'						 => esc_attr__( 'Choose whether you want to edit just the content area or the entire page', 'ba-cheetah' ),
	'tourPageSettings'				 => esc_attr__( 'Access the page background, header and footer settings from here', 'ba-cheetah' ),
	'tourTemplates'                  => esc_attr__( 'Choose a template or start from scratch!.', 'ba-cheetah' ),
	'tourAddRows'                    => esc_attr__( 'Add multi-column rows', 'ba-cheetah' ),
	'tourAddContent'                 => esc_attr__( 'Drag elements to the page and build your website.', 'ba-cheetah' ),
	'tourDoneButton'                 => esc_attr__( "Click here to publish Your page", 'ba-cheetah' ),
	'tourMobileEditing'              => esc_attr__( "Edit for desktop, tablet and mobile", 'ba-cheetah' ),
	'tourFinishedTitle'              => esc_attr__( "Congratulations!", 'ba-cheetah' ),
	'tourFinished'                   => esc_attr__( "You are now ready to start building!", 'ba-cheetah' ),
	'unloadWarning'                  => esc_attr__( 'The settings you are currently editing will not be saved if you navigate away from this page.', 'ba-cheetah' ),
	'viewKnowledgeBase'              => esc_attr__( 'View the Knowledge Base', 'ba-cheetah' ),
	'validateRequiredMessage'        => esc_attr__( 'This field is required.', 'ba-cheetah' ),
	'schemaAllRequiredMessage'       => esc_attr__( 'All Structured Data fields are required.', 'ba-cheetah' ),
	'visitForums'                    => esc_attr__( 'Contact Support', 'ba-cheetah' ),
	'watchHelpVideo'                 => esc_attr__( 'Watch the Video', 'ba-cheetah' ),
	'welcome'	                     => esc_attr__( 'Welcome to Builderall Builder for Wordpress!', 'ba-cheetah' ),
	'welcomeMessage'                 => esc_attr__( 'Click Start to learn the basic features of the builder', 'ba-cheetah' ),
	'widget'                         => esc_attr__( 'Widget', 'ba-cheetah' ),
	'widgetsCategoryTitle'           => esc_attr__( 'WordPress Widgets', 'ba-cheetah' ),
	'uncategorized'                  => esc_attr__( 'Uncategorized', 'ba-cheetah' ),
	'yesPlease'                      => esc_attr__( 'Yes Please!', 'ba-cheetah' ),
	'notificationDradDropActivated'	 => esc_attr__( 'By activating drag and drop you can drag elements into the content area. Come on?', 'ba-cheetah' ),
	'changeLayoutModeMessage'		 => esc_attr__( 'Are you sure you want to change the layout mode? Save all your changes first as will need to reload the page', 'ba-cheetah' ),
	'dropModuleRecursivellyMessage'	 => esc_attr__( 'Nesting elements with drag and drop enabled is not allowed' ),
	'cantDeleteLastRowInside'		 => esc_attr__( 'Grid system inside element cannot be defragmented' ),
	'noScriptWarn'                   => array(
		'heading' => esc_attr__( 'Settings could not be saved.', 'ba-cheetah' ),
		// translators: %s : User Role
		'message' => sprintf( esc_attr__( 'These settings contain sensitive code that is not allowed for your user role (%s).', 'ba-cheetah' ), BACheetahUtils::get_current_user_role() ),
		'global'  => esc_attr__( 'These settings contain sensitive code that is not allowed as DISALLOW_UNFILTERED_HTML has been set globally via wp-config.', 'ba-cheetah' ),
	),
	'savedStatus'                    => array(
		'saving'               => esc_attr__( 'Saving...', 'ba-cheetah' ),
		'savingTooltip'        => esc_attr__( 'The layout is currently being saved', 'ba-cheetah' ),
		'saved'                => esc_attr__( 'Saved', 'ba-cheetah' ),
		'savedTooltip'         => esc_attr__( 'The layout is saved', 'ba-cheetah' ),
		'edited'               => esc_attr__( 'Edited', 'ba-cheetah' ),
		'editedTooltip'        => esc_attr__( 'This layout has unpublished changes', 'ba-cheetah' ),
		'editedWarning'        => esc_attr__( 'This layout has unpublished changes. If you discard this draft all of your previously unpublished changes will be lost.', 'ba-cheetah' ),
		'editedWarningDismiss' => esc_attr__( 'Ok, got it!', 'ba-cheetah' ),
		'noChanges'            => esc_attr__( 'Nothing new to publish', 'ba-cheetah' ),
		'publishing'           => esc_attr__( 'Publishing Changes', 'ba-cheetah' ),
		'publishingTooltip'    => esc_attr__( 'Changes being published', 'ba-cheetah' ),
		'nothingToSave'        => esc_attr__( 'No new changes to save', 'ba-cheetah' ),
		'hasAlreadySaved'      => esc_attr__( 'Your changes are saved', 'ba-cheetah' ),
	),
	'typeLabels'                     => array(
		'template' => esc_attr__( 'Template', 'ba-cheetah' ),
		'module'   => esc_attr__( 'Element', 'ba-cheetah' ),
		'row'      => esc_attr__( 'Row', 'ba-cheetah' ),
		'colGroup' => esc_attr__( 'Column Group', 'ba-cheetah' ),
		'widget'   => esc_attr__( 'Widget', 'ba-cheetah' ),
	),
	'categoryMeta'                   => array(
		'landing' => array(
			'name' => esc_attr__( 'Landing Pages', 'ba-cheetah' ),
		),
		'company' => array(
			'name' => esc_attr__( 'Content Pages', 'ba-cheetah' ),
		),
	),
	'notifications'                  => array(
		'title'   => esc_attr__( 'Notifications', 'ba-cheetah' ),
		'loading' => esc_attr__( 'Loading...', 'ba-cheetah' ),
		'none'    => esc_attr__( 'No Notifications.', 'ba-cheetah' ),
	),
	'module_import'                  => array(
		'copied' => esc_attr__( 'Copied!', 'ba-cheetah' ),
		'error'  => esc_attr__( 'Import Error!', 'ba-cheetah' ),
		'type'   => esc_attr__( 'Missing header or wrong element type!', 'ba-cheetah' ),
	),
	'confirmLayoutSave' => esc_attr__('When saving the layout change or editor will be reloaded and unsaved changes may be lost, do you want to continue?', 'ba-cheetah'),
	'booking' => array(
		'embed_all_groups' => esc_attr__('Embed all groups'),
		'select_calendar' => esc_attr__('Select a calendar'),
		'embed_only' => esc_attr__('Embed only')
	),
	'mailingboss_form' => array(
		'select_list' => esc_attr__('Select a list', 'ba-cheetah')
	),
    'video_hosting' => array(
        'select_video_hosting' => esc_attr__('Select a video hosting'),
    ),
    'webinar' => array(
        'select_webinar' => esc_attr__('Select a webinar'),
    ),

	// These are API returns
	// We must insert here all texts that the API returns
    'apiResponseMessages' => array(
        __('User activated!', 'ba-cheetah'),
		__('The token has expired!', 'ba-cheetah'),
		__('Please, pay for Pro access before active it! If you already paid, contact the support!', 'ba-cheetah'),
		__('The Token does not match, is it correct? Please, try again!', 'ba-cheetah'),
		__('We do not have notice that this user has bought Builderall Builder for Wordpress. If you have bought it, try again later or contact our support team!', 'ba-cheetah'),
		__('Please, pay for Pro access before active it! If you already paid, contact the support!', 'ba-cheetah'),
    ),
) ) ) . ';';

BACheetahFonts::js();

?>
</script>
